DFE-Digital/eligibility-checking-engine

CheckYourEligibility.Domain/Requests/CheckEligibilityRequest.cs
CheckYourEligibility.sln
FreeSchoolMealsResponseModel.cs
TestProject1/API/GET_FreeSchoolMealsGUIDStatus.cs
TestProject1/API/POST_FreeSchoolMeals.cs
TestProject1/CheckYourEligibility.SystemTests.csproj
TestProject1/Utilities/ApiHelper.cs
TestProject1/Utilities/CommonMethods.cs
TestProject1/Utilities/JSON/RequestBody.json
TestProject1/Utilities/Models/FreeSchoolMealsResponseModel.cs
TestProject1/Utilities/Models/FreeSchoolMealsStatusResponseModel.cs

Created system tests using playwright and NUnit.
Created Mode for request body and response.
Added ApiHelper and Common Methods

System tests added

---

tests/cypress/API/01 - Import Data/ImportSchoolData.cy.ts
tests/cypress/API/02 - Authorisation/Auth.cy.ts
tests/cypress/API/03 - Eligibility/GetEligibilitySoftCheckStatus.cy.ts
tests/cypress/API/04 - Application/GetApplication.cy.ts
tests/cypress/API/04 - Application/PostApplication.cy.ts
tests/cypress/API/04 - Application/SearchApplication.cy.ts
tests/cypress/API/04 - Application/UpdateApplicationStatus.cy.ts
tests/cypress/API/05 - Schools/SchoolSearch.cy.ts
tests/cypress/support/apiHelpers.ts
tests/cypress/support/commands.ts

Import test fixed
Added check for token expiry
Update the tests with expected school data

Import tests update

---

CheckYourEligibility.APIUnitTests/AdministrationControllerTests.cs
CheckYourEligibility.APIUnitTests/Properties/Resources.Designer.cs
CheckYourEligibility.APIUnitTests/Properties/Resources.resx
CheckYourEligibility.APIUnitTests/Resources/exampleHMRC.xml
CheckYourEligibility.APIUnitTests/Resources/exampleHMRC_empty.xml
CheckYourEligibility.Data/EligibilityCheckContext.cs
CheckYourEligibility.Data/IEligibilityCheckContext.cs
CheckYourEligibility.Domain/Constants/Admin.cs
CheckYourEligibility.ServiceUnitTests/AdministrationServiceTests.cs
CheckYourEligibility.Services/AdministrationService.cs
CheckYourEligibility.Services/CheckYourEligibility.Services.csproj
CheckYourEligibility.Services/Interfaces/IAdministration.cs
CheckYourEligibility.Services/XmlImport/HomeOffice.cs
CheckYourEligibility.WebApp/CheckYourEligibility.WebApp.csproj
CheckYourEligibility.WebApp/Controllers/AdministrationController.cs

#167875
Import HMRC data 
@NyWeb

ImportHMRCData

---

CheckYourEligibility.Data.Migrations/Migrations/20240606105543_ApplicationHash.Designer.cs
CheckYourEligibility.Data.Migrations/Migrations/20240606105543_ApplicationHash.cs
CheckYourEligibility.Data/Models/Application.cs
CheckYourEligibility.ServiceUnitTests/AuditServiceTests.cs
CheckYourEligibility.ServiceUnitTests/FsmApplicationServiceTests .cs
CheckYourEligibility.ServiceUnitTests/FsmCheckEligibilityServiceTests.cs
CheckYourEligibility.ServiceUnitTests/UserServiceTests.cs
CheckYourEligibility.Services/FsmApplicationService.cs
CheckYourEligibility.Services/FsmCheckEligibilityService.cs
README.md

hash record

---

CheckYourEligibility.APIUnitTests/FreeSchoolMealsControllerTests.cs

updated to get coverage
#167877

covered tests

---

CheckYourEligibility.Domain/Requests/ApplicationRequestSearch.cs
CheckYourEligibility.ServiceUnitTests/FsmApplicationServiceTests .cs
CheckYourEligibility.Services/FsmApplicationService.cs

expanded application search

---

CheckYourEligibility.WebApp/Program.cs

Adds an authorise button to the swagger page,  use login to get bearer token

Authorise swagger

---

tests/README.md

readme added

---

.gitignore
pipeline/continuous-deployment.yml
tests/cypress/API/02 - Authorisation/Auth.cy.ts
tests/cypress/API/03 - Eligibility/GetEligibilitySoftCheckStatus.cy.ts
tests/cypress/API/03 - Eligibility/PostEligibilitySoftCheck.cy.ts
tests/cypress/API/04 - Application/GetApplication.cy.ts
tests/cypress/API/04 - Application/PostApplication.cy.ts
tests/cypress/API/04 - Application/SearchApplication.cy.ts
tests/cypress/API/04 - Application/UpdateApplicationStatus.cy.ts
tests/cypress/support/commands.ts
tests/package-lock.json
tests/package.json

Updated existing Cypess tests to pass

Fix update cypress tests

---

CheckYourEligibility.Services/FsmCheckEligibilityService.cs
CheckYourEligibility.Services/HashService.cs

get hash was not working due to the surname not being set

correct hashing data

---

tests/cypress.config.ts

Added a retry step to the Cypress tests (1)

added retry

---

CheckYourEligibility.Services/FsmCheckEligibilityService.cs

Added processing time metric, added log metric for dwp error

add metric

---

CheckYourEligibility.WebApp/Program.cs

Added healthcheck endpoint to API webApp.

Added healthcheck endpoint to API webApp.

---

pipeline/continuous-deployment.yml
tests/cypress/API/04 - Application/GetApplication.cy.ts
tests/cypress/API/04 - Application/PostApplication.cy.ts
tests/package-lock.json

Added User_ID to get/Post application requests

Update tests to include user

---

CheckYourEligibility.APIUnitTests/AdministrationControllerTests.cs
CheckYourEligibility.APIUnitTests/ApplicationControllerTests.cs
CheckYourEligibility.APIUnitTests/EligibilityCheckControllerTests.cs
CheckYourEligibility.APIUnitTests/SchoolsControllerTests.cs
CheckYourEligibility.APIUnitTests/UsersControllerTests.cs
CheckYourEligibility.Services/ApplicationService.cs
CheckYourEligibility.WebApp/Controllers/AdministrationController.cs
CheckYourEligibility.WebApp/Controllers/ApplicationController.cs
CheckYourEligibility.WebApp/Controllers/EligibilityController.cs
CheckYourEligibility.WebApp/Controllers/SchoolsController.cs
CheckYourEligibility.WebApp/Controllers/UsersController.cs

Ensures that all controllers trap errors if generated from the service

resolved middleware response issues

---

CheckYourEligibility.APIUnitTests/EligibilityCheckControllerTests.cs
CheckYourEligibility.Data/Mappings/MappingProfile.cs
CheckYourEligibility.Domain/CheckYourEligibility.Domain.csproj
CheckYourEligibility.Domain/Requests/CheckEligibilityRequest.cs
CheckYourEligibility.Domain/Responses/CheckEligibilityBulkResponse.cs
CheckYourEligibility.Domain/Responses/CheckEligibilityItemResponse.cs
CheckYourEligibility.ServiceUnitTests/CheckEligibilityServiceTests.cs
CheckYourEligibility.Services/ApplicationService.cs
CheckYourEligibility.Services/CheckEligibilityService.cs
CheckYourEligibility.Services/Interfaces/ICheckEligibility.cs

Tidied models to support new service creation

tidied to support new service

---

tests/README.md
tests/cypress.config.ts
tests/cypress/API/03 - Eligibility/GetEligibilitySoftCheck.cy.ts
tests/cypress/API/03 - Eligibility/GetEligibilitySoftCheckStatus.cy.ts
tests/cypress/API/03 - Eligibility/PostEligibilitySoftCheck.cy.ts
tests/cypress/API/04 - Application/GetApplication.cy.ts
tests/cypress/API/04 - Application/PostApplication.cy.ts
tests/cypress/API/04 - Application/SearchApplication.cy.ts
tests/cypress/API/04 - Application/UpdateApplicationStatus.cy.ts
tests/cypress/API/05 - Schools/SchoolSearch.cy.ts
tests/cypress/support/commands.ts
tests/cypress/support/e2e.ts
tests/cypress/support/interfaces.ts
tests/cypress/support/requestBodies.ts
tests/package-lock.json
tests/package.json

Refactored API Cypress tests.
Refactored and updated commands.ts 
added some new info to readMe

Cypress refactor name fix

---

tests/cypress.config.ts

removed variable during the testing process re added

added missing variable

---

CheckYourEligibility.APIUnitTests/LoginControllerTests.cs
CheckYourEligibility.APIUnitTests/Usecases/AuthenticateUserUseCaseTests.cs
CheckYourEligibility.Domain/JwtConfig.cs
CheckYourEligibility.Domain/SystemUser.cs
CheckYourEligibility.WebApp/Controllers/LoginController.cs
CheckYourEligibility.WebApp/UseCases/AuthenticateUserUseCase.cs
tests/README.md
tests/cypress/API/02 - Authorisation/Auth.cy.ts
tests/cypress/support/requestBodies.ts

- Standardise JWT endpoint
- Move from Username & Password to Client_ID & Client Secret - standard JWT protocol
- This commit supports both Username & Password and Client_ID & Client Secret

jwt related updates

---

CheckYourEligibility.APIUnitTests/ApplicationControllerTests.cs
CheckYourEligibility.Data.Migrations/Migrations/20250312123327_AddScopeColumnToAudit.Designer.cs
CheckYourEligibility.Data.Migrations/Migrations/20250312123327_AddScopeColumnToAudit.cs
CheckYourEligibility.Data/Models/Audit.cs
CheckYourEligibility.Domain/Requests/AuditData.cs
CheckYourEligibility.Services/AuditService.cs
CheckYourEligibility.WebApp/Controllers/ApplicationController.cs
CheckYourEligibility.WebApp/Extensions/ClaimsPrincipalExtensions.cs
CheckYourEligibility.WebApp/ProgramExtensions.cs
CheckYourEligibility.WebApp/UseCases/SearchApplicationsUseCase.cs
CheckYourEligibility.WebApp/appsettings.json

- Validate scope
- Add scope to audit table

feat: updated code to validate scope and log scope in Audit table

---

tests/README.md

**Documentation Update**
An update to the README for setting up Cypress test runner

Update cypress install instructions in test folder

---

CheckYourEligibility.API.Tests/Gateways/ApplicationServiceTests .cs
CheckYourEligibility.API/Boundary/Requests/ApplicationRequest.cs
CheckYourEligibility.API/Boundary/Responses/ApplicationResponse.cs
CheckYourEligibility.API/Boundary/Shared/ApplicationEvidence.cs
CheckYourEligibility.API/Domain/Application.cs
CheckYourEligibility.API/Domain/ApplicationEvidence.cs
CheckYourEligibility.API/Factories/MappingProfile.cs
CheckYourEligibility.API/Gateways/ApplicationGateway.cs
CheckYourEligibility.API/Infrastructure/EligibilityCheckContext.cs
CheckYourEligibility.API/Migrations/20250414113327_AddApplicationEvidence.Designer.cs
CheckYourEligibility.API/Migrations/20250414113327_AddApplicationEvidence.cs
tests/cypress/API/04 - Application/GetApplication.cy.ts
tests/cypress/support/commands.ts
tests/cypress/support/requestBodies.ts

- updated boundary objects for evidence
- more details on the implementation to be added

feat: added evidence class

---

CheckYourEligibility.API/Domain/Application.cs
CheckYourEligibility.API/Migrations/20250618154353_AddEligibilityEndDateToApplication.Designer.cs
CheckYourEligibility.API/Migrations/20250618154353_AddEligibilityEndDateToApplication.cs

todo: check if related code needs to be updated

feat: added eligibility end date column to Applications table

---

CheckYourEligibility.API.Tests/Controllers/EligibilityCheckControllerTests.cs
CheckYourEligibility.API/Domain/Audit.cs
CheckYourEligibility.API/Domain/WorkingFamiliesEvent.cs
CheckYourEligibility.API/Gateways/CheckEligibilityGateway.cs
CheckYourEligibility.API/Migrations/20250707171036_WorkingFamiliesEventAddSubmissionDate.Designer.cs
CheckYourEligibility.API/Migrations/20250707171036_WorkingFamiliesEventAddSubmissionDate.cs
CheckYourEligibility.API/Migrations/20250708091320_AuditTableIncreaseScopeLength.Designer.cs
CheckYourEligibility.API/Migrations/20250708091320_AuditTableIncreaseScopeLength.cs
tests/cypress/API/03 - Eligibility/GetEligibilitySoftCheckStatus.cy.ts
tests/cypress/API/03 - Eligibility/PostEligibilitySoftCheck.cy.ts
tests/cypress/support/requestBodies.ts

1. Introduce process logic for a WF check. 
2. Cypress Tests for Working Families: 
Invalid Eligibility Code 
Valid post check 
3. Increase char length for scope in Audit table to accommodate the new additional scopes.
4. Add SubmissionDate for WorkingFamiliesEvents.
Ticket: https://dev.azure.com/dfe-gov-uk/Solutions%20Development/_boards/board/t/ECS/Stories?System.AssignedTo=%40me&workitem=222704

222704 wf introduce noteligible status to wf api

---

CheckYourEligibility.API.Tests/Controllers/EligibilityCheckControllerTests.cs
CheckYourEligibility.API.Tests/Usecases/CheckEligibilityBulkUseCaseTests.cs
CheckYourEligibility.API.Tests/Usecases/GetEligibilityCheckItemUseCaseTests.cs
CheckYourEligibility.API/Boundary/Requests/CheckEligibilityRequest.cs
CheckYourEligibility.API/Controllers/EligibilityController.cs
CheckYourEligibility.API/Gateways/CheckEligibilityGateway.cs
CheckYourEligibility.API/Gateways/Interfaces/ICheckEligibility.cs
CheckYourEligibility.API/Usecases/CheckEligibilityBulkUseCase.cs

1. Amending batch request result response to include WF. 
2. Adding example for swagger for WF bulk checks.
3. Introducing new bulk request for working families.
Ticket: https://dev.azure.com/dfe-gov-uk/Solutions%20Development/_boards/board/t/ECS/Stories?System.AssignedTo=Lili.NEDELEVA%40EDUCATION.GOV.UK&workitem=223287

223287 wf bulkchecks prost and process

---

CheckYourEligibility.API/Gateways/CheckEligibilityGateway.cs
CheckYourEligibility.API/Gateways/HashGateway.cs

Add required data for working families in hash
https://dev.azure.com/dfe-gov-uk/Solutions%20Development/_boards/board/t/ECS/Stories?System.AssignedTo=%40me&workitem=217200
And Validity start date from database into API response
And Validity end date from database into API response
And Grace period end date calculated on the fly into API response, give details
And Parent last name
And Eligibility Code returned

Add required data for working families in hash

---

CheckYourEligibility.API.Tests/Gateways/CheckEligibilityServiceTests.cs
CheckYourEligibility.API/Boundary/Responses/CheckEligibilityItemResponse.cs
CheckYourEligibility.API/Domain/Enums/CheckProcessData.cs
CheckYourEligibility.API/Gateways/CheckEligibilityGateway.cs
CheckYourEligibility.API/Gateways/HashGateway.cs

Standardise API response fields across claim types
https://dfe-gov-uk.visualstudio.com/Solutions%20Development/_workitems/edit/225992
Add parentLastName, childDateOfBirth, nationalInsuranceNumber to WF check data response
Add values to CheckProcessData
Use values in hash calculation

225992 wf standardise return fields

---

tests/cypress/fixtures/WorkingFamiliesTestDataVendors.csv

https://dfe-gov-uk.visualstudio.com/Solutions%20Development/_workitems/edit/227312
Maintain test data. Excel version attached to ticket.

update WF test data

---

CheckYourEligibility.API/Boundary/Requests/CheckEligibilityRequest.cs
CheckYourEligibility.API/Domain/Constants/ErrorMessages/ApplicationValidationMessages.cs
CheckYourEligibility.API/Domain/Enums/CheckProcessData.cs
CheckYourEligibility.API/Domain/Validation/CheckEligibilityRequestDataValidator.cs
CheckYourEligibility.API/Gateways/CheckEligibilityGateway.cs
tests/cypress/API/03 - Eligibility/PostEligibilityBulkCheck.cy.ts
tests/cypress/API/03 - Eligibility/PostEligibilitySoftCheck.cy.ts
tests/cypress/support/requestBodies.ts

Ticket: https://dfe-gov-uk.visualstudio.com/Solutions%20Development/_workitems/edit/230965
- Makes lastname optional for WF checks
- Allows empty string for lastname for WF checks
- Updates lastname validation for WF checks to return an appropriate validation message
- adds null or empty lastname check to query to find WF event

230965 wf optional lastname

---

CheckYourEligibility.API/Domain/Constants/ErrorMessages/ApplicationValidationMessages.cs
CheckYourEligibility.API/Domain/Validation/ApplicationRequestValidator.cs
CheckYourEligibility.API/Domain/Validation/CheckEligibilityRequestDataValidator.cs
CheckYourEligibility.API/Domain/Validation/DataValidation.cs
tests/cypress/support/requestBodies.ts

Ticket: https://dfe-gov-uk.visualstudio.com/Solutions%20Development/_workitems/edit/235214
- Implements NASS validation to align with frontend. Applied to both applications and eligibility checks

216658 implement nass validation

---

pipeline/continuous-deployment.yml
pipeline/continuous-integration.yml
tests/cypress/API/03 - Eligibility/GetEligibilitySoftCheck.cy.ts

Problem: test for WF response properties validation in PP fails because there is no available test data.
Add flag to check env. Skip PP for WF test where test data is not available.

Add flag to check env. Skip pp for wf test where test data is not available

---

CheckYourEligibility.API/Gateways/CheckEligibilityGateway.cs
CheckYourEligibility.API/appsettings.json
tests/cypress/fixtures/WorkingFamiliesTestDataVendors.csv

1. Adding method to handle test data for status 'eligible'.
Ticket : https://dev.azure.com/dfe-gov-uk/Solutions%20Development/_boards/board/t/ECS/Stories?System.AssignedTo=%40me&workitem=235445

235445 wf testing for status eligible

---

CheckYourEligibility.API.Tests/Controllers/EstablishmentControllerTests.cs
CheckYourEligibility.API.Tests/Gateways/SchoolSearchServiceTests.cs
CheckYourEligibility.API.Tests/Usecases/SearchEstablishmentsUseCaseTests.cs
CheckYourEligibility.API/Controllers/EstablishmentController.cs
CheckYourEligibility.API/Gateways/EstablishmentSearchGateway.cs
CheckYourEligibility.API/Gateways/Interfaces/IEstablishmentSearch.cs
CheckYourEligibility.API/Usecases/SearchEstablishmentsUseCase.cs

Ticket: https://dfe-gov-uk.visualstudio.com/Solutions%20Development/_workitems/edit/237183/
Adds mat parameter to establishment search
If mat provided it filters on establishments that are part of the mat

Add MAT parameter to establishment search
